name: Deploy Angular to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --configuration production

      - name: Push to cPanel repo
        run: |
          git config --global user.email "deploy@github.com"
          git config --global user.name "GitHub CI"
          git remote add cpanel https://x-access-token:${{ secrets.CPANEL_TOKEN }}@github.com/bastirojasv/crc-ecommerce.git
          git push cpanel main --force
