---
deployment:
  tasks:
    - export DEPLOYPATH=dist/crc-ecommerce/browser
    - echo "ðŸ”„ Iniciando deploy" > deploy.log
    - /bin/ls -la $DEPLOYPATH >> deploy.log 2>&1

    # Limpiar contenido anterior de public_html
    - echo "ðŸ§¹ Limpiando /home/crcingen/public_html" >> deploy.log
    - /bin/rm -rf /home/crcingen/public_html/* >> deploy.log 2>&1

    # Copiar nueva build
    - echo "ðŸ“¦ Copiando archivos..." >> deploy.log
    - /bin/cp -Rvf $DEPLOYPATH/* /home/crcingen/public_html/ >> deploy.log 2>&1

    # Copiar archivo .htaccess desde el repositorio
    - echo "ðŸ” Restaurando .htaccess" >> deploy.log
    - /bin/cp -v .htaccess /home/crcingen/public_html/.htaccess >> deploy.log 2>&1

    - echo "âœ… Deploy finalizado" >> deploy.log
