---
deployment:
  tasks:
    - export DEPLOYPATH=dist/crc-ecommerce/browser
    - echo "Inicio del deploy" > deploy.log
    - /bin/ls -la $DEPLOYPATH >> deploy.log 2>&1
    - /bin/cp -Rvf $DEPLOYPATH/* ./ >> deploy.log 2>&1
    - echo "Deploy finalizado" >> deploy.log
