name: Build & Deploy Angular to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npx ng build crc-ecommerce --configuration production

      - name: Ensure .htaccess is present
        run: |
          if [ ! -f .htaccess ]; then
            echo "⚠️ ERROR: Falta el archivo .htaccess" && exit 1
          fi

      - name: Push to cPanel-connected repo
        run: |
          git config --global user.email "deploy@github.com"
          git config --global user.name "GitHub CI"
          git remote add cpanel https://x-access-token:${{ secrets.CPANEL_TOKEN }}@github.com/bastirojasv/crc-ecommerce.git
          git add dist/ .htaccess .cpanel.yml
          git commit -m "Auto deploy desde GitHub Actions 🚀" || echo "Nada que commitear"
          git push cpanel main --force
